apps/sku_lists/src/components/SkuListForm/SkuListForm.tsx
apps/sku_lists/src/hooks/useSkuListDetails.tsx
apps/sku_lists/src/pages/SkuListDetails.tsx
apps/sku_lists/src/pages/SkuListEdit.tsx

Enforced `SKU list`  app to avoid `SKU list items` to be edited if `SKU list` is linked to any `Bundle`.
If the `Edit` button is clicked the form will permit only to edit the `Name` field.

Enforce `SKU list` app

---

apps/stock_transfers/src/data/dictionaries.ts
apps/stock_transfers/src/data/filters.ts
apps/stock_transfers/src/data/lists.test.ts
apps/stock_transfers/src/data/lists.ts
apps/stock_transfers/src/pages/Home.tsx

Closes commercelayer/issues-app#220
Added support for `upcoming` status in `Stock Transfers` app.
- [  ] Make sure to add/update documentation regarding your changes.

Add support for `upcoming` status in `Stock Transfers` app

---

apps/customers/src/components/CustomerLastOrders.tsx
apps/customers/src/hooks/useCustomerOrdersList.tsx
apps/customers/src/pages/CustomerOrders.tsx

Closes commercelayer/issues-app/issues/222
- Sorted customer orders by `placed_at`.
- Update the UI of the `See all` button of `Orders` list.

Sort `Customer` orders by `placed_at`

---

apps/exports/src/data/relationships.ts

Closes https://github.com/commercelayer/issues-app/issues/135
I have updated the list of available include when exporting shipments.
Since now API allows also to include `origin_address`, `shipping_address` and `parcels`.

Update include list when exporting shipments

---

apps/stock_transfers/src/components/StockTransferTimeline.tsx

Fix attachment creation in `Stock transfers` app by setting the correct resource type used to create the `attachment` and by adding the missing visualization of the attachments in the list.

Fix attachment creation in `Stock transfers` app

---

apps/bundles/src/pages/BundleDetails.tsx
apps/orders/src/pages/OrderDetails.tsx
apps/shipments/src/pages/ShipmentDetails.tsx
apps/skus/src/pages/SkuDetails.tsx

Readapt top spacing of details pages in some app where the `ResourceTags` component was moved at the bottom.

Fix spacings in some details pages

---

apps/orders/src/components/OrderSummary/SummaryRows.tsx
apps/orders/src/components/OrderSummary/utils.tsx

Show whether taxes are included or not in the order summary.

Show whether taxes are included or not in the order summary

---

apps/skus/src/pages/LinkDetails.tsx
apps/skus/src/pages/LinkEdit.tsx
apps/skus/src/pages/LinkNew.tsx
apps/skus/src/pages/SkuDetails.tsx
packages/common/src/components/LinkListRow.tsx
packages/common/src/components/LinkListTable.tsx

Reorganized `SKUs` app detail page with tabs by:
- Moving `Links` to a first dedicated tab along with the `New link` CTA button previously placed inside the top toolbar
- Adding a `Info` tab that contains all the other blocks like `Info`, `Details`, `Tags` and `Metadata`

Reorganize `SKUs` app detail page with tabs

---

apps/skus/src/utils/getSkuFromFormValues.ts

Closes commercelayer/issues-app/issues/244
Fixed `SKUs` edit form to send `shipping_category` relationship with the correct relationship value depending on if it is to be filled or it needs to be nullified

Fix `SKUs` edit form

---

apps/skus/src/pages/SkuEdit.tsx

Fixed default values in edit page of `skus` app to have the correct empty value of the `shipping_category` relationship.

Fix edit form default values in `skus` app

---

apps/price_lists/src/components/ListItemPrice.tsx
apps/price_lists/src/components/ListItemSku.tsx
apps/price_lists/src/components/PriceForm.tsx
apps/price_lists/src/components/PriceListSelector.tsx
apps/price_lists/src/data/routes.ts
apps/price_lists/src/hooks/usePriceDetails.tsx
apps/price_lists/src/hooks/usePriceListDetails.tsx
apps/price_lists/src/pages/Home.tsx
apps/price_lists/src/pages/PriceDetails.tsx
apps/price_lists/src/pages/PriceEdit.tsx
apps/price_lists/src/pages/PriceNew.tsx
apps/price_lists/src/pages/PricesList.tsx

Add `All prices` page in `price_lists` app to show the full list of prices without any price lists constraint.
This change caused several changes in app's navigation and forms to support the old price list based navigation in a sort of optional way at the price list URL level.
In addition, when a price is created from the All prices page a new price list select is shown in order to set the required price list information and update the currency code used to configure the price and origina price fields.

Add `All prices` page in `price_lists` app

---

apps/inventory/src/App.tsx
apps/inventory/src/components/ListItemSku.tsx
apps/inventory/src/components/ListItemStockItem.tsx
apps/inventory/src/components/ListItemStockLocation.tsx
apps/inventory/src/components/StockItemForm.tsx
apps/inventory/src/components/StockItemInfo.tsx
apps/inventory/src/components/StockLocationSelector.tsx
apps/inventory/src/data/filters.ts
apps/inventory/src/data/routes.ts
apps/inventory/src/hooks/useStockLocationDetails.tsx
apps/inventory/src/pages/Home.tsx
apps/inventory/src/pages/StockItemDetails.tsx
apps/inventory/src/pages/StockItemEdit.tsx
apps/inventory/src/pages/StockItemNew.tsx
apps/inventory/src/pages/StockItemsList.tsx

Add `All inventory` page in `inventory` app to show the full list of stock items without any stock location constraint.
This change caused several changes in app's navigation and forms to support the old stock location based navigation in a sort of optional way of the stock location URL level.
In addition, when a `stock item` is created from the `All inventory` page a new `stock location` select is shown in order to set the required stock location information.

Add `All inventory` page in `inventory` app

---

apps/orders/src/components/OrderSummary/hooks/useAddItemOverlay.tsx

New order and edit order from orders app can add bundles without a market.
1. [app-bundles] - Create a bundle without selecting a Market
2. [app-orders] - Create a new order within a Market with same currency code.
3. [app-orders] - Select "Add a bundle". The bundle is now visible and selectable.

New order and edit order from orders app can add bundles without a market

---

apps/inventory/src/pages/Home.tsx

Enhanced home page of `Inventory` app by:
- hiding the search bar if no stock locations are available
- hiding also the whole `Browse` section if no stock locations are available and showing the old gray empty state in caso no stock locations are available

Enhance home page of `Inventory` app

---

apps/orders/src/components/OrderAddresses.tsx

Closes commercelayer/issues-app#234 commercelayer/issues-app#91
Now is possible to set up the shipping and billing addresses directly from the order creation page.

Possibility to set up the shipping and billing addresses from the order creation page

---

apps/shipments/src/components/FormPackingFieldPackages.tsx
apps/shipments/src/components/ShipmentSteps.tsx
apps/shipments/src/data/packingFormSchema.ts
apps/shipments/src/hooks/useCreateParcel.tsx
apps/shipments/src/pages/Packing.tsx

Closes commercelayer/issues-app#206
- auto select first package when is the only one
----
- set "packing" badge as warning variant 
----
- Improve UX of the packages selector, when more than 4 packages are available to align to all others autocomplete/select

Improve UI/UX for package selector in shipments app

---

apps/subscriptions/package.json
apps/subscriptions/src/App.tsx
apps/subscriptions/src/components/ListEmptyState.tsx
apps/subscriptions/src/data/filters.ts
apps/subscriptions/src/data/frequencies.ts
apps/subscriptions/src/data/routes.ts
apps/subscriptions/src/hooks/useSubscriptionModelsFrequencies.tsx
apps/subscriptions/src/pages/Filters.tsx
apps/subscriptions/src/pages/SubscriptionsList.tsx
pnpm-lock.yaml

Added filters in home page of `subscriptions` app.
Frequency filters are calculated by generating a unique list of frequencies from organization's `subscription_models` and then used relying on the `frequency_matches` filter type.

Add `subscriptions` filters

---

apps/customers/src/components/ListEmptyState.tsx

Closes commercelayer/issues-app/issues/253
Fixed the behavior of the empty state block in customers list. Actually it was not showing the create customer button in history list where it was expected to be.

Fix list empty state behavior in `customers` app

---

apps/inventory/src/pages/Home.tsx
apps/price_lists/src/pages/Home.tsx

This pull request refactors how resource lists are rendered in the `Home` component for both the inventory and price lists pages. The main changes include replacing the manual mapping of list items with the `ResourceList` component.
Refactoring resource list rendering:
* [`apps/inventory/src/pages/Home.tsx`](diffhunk://#diff-941af74a62bc56768558f0a00aa6a772f0546c0c726e02c91d3fe44b84a979e0L25-R25): Replaced the manual mapping of `stockLocation` items with the `ResourceList` component, using `ListItemStockLocation` as the item template. [[1]](diffhunk://#diff-941af74a62bc56768558f0a00aa6a772f0546c0c726e02c91d3fe44b84a979e0L25-R25) [[2]](diffhunk://#diff-941af74a62bc56768558f0a00aa6a772f0546c0c726e02c91d3fe44b84a979e0L77-R77)
* [`apps/price_lists/src/pages/Home.tsx`](diffhunk://#diff-4ddb8d5e …

Replace static list with ResourceList in inventory and price_lists apps

---

apps/subscriptions/src/App.tsx
apps/subscriptions/src/components/ListItemSubscriptionOrder.tsx
apps/subscriptions/src/components/SubscriptionOrders.tsx
apps/subscriptions/src/data/routes.ts
apps/subscriptions/src/mocks/index.ts
apps/subscriptions/src/mocks/resources/orders.ts
apps/subscriptions/src/pages/SubscriptionDetails.tsx
apps/subscriptions/src/pages/SubscriptionOrders.tsx

Added the `Recurring orders` table inside the subscription `detail` page.
The list is limited to a maximum of 5 items in detail page.
The full `Recurring orders` list, if needed, is accessible by clicking an optional `See all` button, visibile only if more then 5 orders are found.

Add subscription orders table

---

apps/orders/src/components/OrderAddresses.tsx
apps/orders/src/components/OrderCustomer.tsx
apps/orders/src/components/OrderSummary/hooks/useActionButtons.tsx
apps/orders/src/components/OrderSummary/hooks/useOrderStatus.tsx
apps/orders/src/components/OrderSummary/orderDictionary.ts
apps/orders/src/hooks/useOrderDetails.tsx
apps/orders/src/hooks/useTriggerAttribute.ts
apps/orders/src/pages/OrderDetails.tsx

closes commercelayer/issues-app#190
closes commercelayer/issues-app#238
> *"If an authorization or capture succeeded, but the associate order is still pending, it can happen that the order is updated and its total amount differs from the authorized or captured one. In this case, you must reset the related transaction by patching it (you need to use integration API credentials on the specific transaction type endpoint) with the _cancel trigger attribute set to true. At the end of the process, the order payment status will still be unpaid so that the payment can be completed with a different payment source."*
> [api-reference](https://docs.commercelayer.io/core/api-reference/transactions#cancelling-transactions)
This PR aims to manage the above situation.
You can try to place the order. …

Manage pending orders with transactions in the order app

---

apps/subscriptions/src/App.tsx
apps/subscriptions/src/components/SubscriptionForm.tsx
apps/subscriptions/src/components/SubscriptionSteps.tsx
apps/subscriptions/src/data/frequencies.ts
apps/subscriptions/src/data/routes.ts
apps/subscriptions/src/pages/SubscriptionDetails.tsx
apps/subscriptions/src/pages/SubscriptionEdit.tsx

Added the top right toolbar in `detail` page with main trigger actions like `Deactivate` / `Activate` / `Cancel subscription` along with `Edit` button to go to the edit form.

Add subscription trigger actions and edit form

---

apps/price_lists/src/components/PriceListForm.tsx

I added the CodeEditor component to the price list rules:

Price list rules with CodeEditor

---

apps/orders/src/data/filters.ts
apps/orders/src/pages/Filters.tsx
apps/orders/src/pages/OrderList.tsx

Closes commercelayer/issues-app/issues/285
Closes commercelayer/issues-app/issues/286
- Added `partially_authorized` option to `Payment Status` filter
- Added a subset of filters to `Carts` view

Enhance orders filters

---

apps/price_lists/src/components/PriceTierForm/PriceTierForm.tsx
apps/price_lists/src/components/PriceTierForm/schema.ts
apps/price_lists/src/pages/PriceTierEdit.tsx
apps/price_lists/src/utils/priceTiers.test.ts
apps/price_lists/src/utils/priceTiers.ts

I have updated the price tiers (volume and frequency) form schema and their default values to better work with input of `type=number`.

Update `price_tiers` form schema

---

apps/promotions/src/data/formConverters/coupon.ts
apps/promotions/src/data/promotions/configs/buy_x_pay_y_promotions.tsx

Closes commercelayer/issues-app#287
Closes commercelayer/issues-app#290
Improve validation schemas in `app-promotions` where input type is `number`.
It now accepts nullish values and error messages are more user friendly.

Improve validation schema for input with type number in promotion forms

---

apps/promotions/src/components/CouponForm.tsx
apps/promotions/src/components/CouponTable.tsx
apps/promotions/src/pages/CouponListPage.tsx

Closes commercelayer/issues-app#291
I have replaced the coupon table with the `ResourceList` component having variant `table`.
In this way we can have infinite scrolling in the view all coupons page (instead of showing only the first 10 items).

Replace static coupon table with `ResourceList` in app-promotions

---

apps/bundles/src/components/BundleForm.tsx

Closes commercelayer/issues-app/issues/282
Hide SKU list selection when editing a bundle to avoid unwanted behavior. The SKU list can be set only during bundle creation.

Hide SKU list selection when editing a bundle

---

apps/shipments/src/main.tsx

This pull request includes a change to the `apps/shipments/src/main.tsx` file to rearrange the order of the `I18NProvider` and `TokenProvider` components. 
Codebase simplification:
* [`apps/shipments/src/main.tsx`](diffhunk://#diff-ba526adf0cce22fce8bb9380149ee42d4188274df9745ac6f07cc6ebdbe687dfL25-R38): Moved the `I18NProvider` component inside the `TokenProvider` component to ensure proper context wrapping and potentially resolve issues related to internationalization and token management.

Set correct order to mount `I18NProvider` in `app-shipments`

---

apps/sku_lists/src/components/ListItemSkuListItem.tsx

Closes commercelayer/issues-app/issues/295
Enabled keyboard quantity selection for SKU lists items and added a 500ms debounce to prevent unwanted PATCH requests while editing quantity.

Enable keyboard quantity selection for SKU lists items

---

apps/orders/src/hooks/useGetCheckoutLink.tsx
apps/orders/src/pages/LinkDetails.tsx

I've fixed an issue related to a wrong visualization of the sales channel used for the generated link.

Show correct sales channel used in an already generated link

---

apps/customers/src/components/CustomerForm.tsx
apps/customers/src/pages/CustomerDetails.tsx
apps/orders/src/components/NewOrder/EditOrderStep.tsx
apps/orders/src/pages/Home.tsx
apps/orders/src/pages/OrderDetails.tsx
apps/orders/src/pages/OrderNew.tsx
apps/returns/src/pages/ReturnDetails.tsx
apps/shipments/src/pages/ShipmentDetails.tsx

Since `shouldRender` method won't be exposed anymore from TokenProvider, we can drop its usage from the apps

Drop usage of shouldRender method

---

apps/exports/src/data/relationships.ts

Closes commercelayer/issues-app/issues/328
Added `returns` and `returns.return_line_items` relationships for `orders` resources in `exports` app.

Add order returns in exports app

---

apps/promotions/src/data/ruleBuilder/form/validator.tsx

Closes commercelayer/issues-app/issues/340
Fixed validation of SKUList rule for minimum qty input in Promotions app.
Actually was evaluating the value of the input as string instead of number.

Fix validation of SKUList rule for minimum qty input

---

apps/promotions/src/components/CouponForm.tsx
apps/promotions/src/data/formConverters/coupon.ts

Fix copy error in names of coupon code length flags.

Fix names of coupon code length flags

---

packages/common/src/components/LinkForm.tsx
packages/common/src/pages/LinkEditPage.tsx
packages/common/src/pages/LinkNewPage.tsx

Closes commercelayer/issues-app/issues/343
Added optional stock location selection in links scope configuration to eventually restrict a link to a particular stock location of a selected market (still required).
The stock location select is at first hidden and will popup as soon as a market is selected with at least `2` or more stock locations with a default empty selection (`All stock locations`).

Add optional stock location selection in links scope configuration

---

apps/orders/src/pages/OrderDetails.tsx

Enforced the order detail toolbar to not show checkout link button when the market is private.
This fix is necessary to manage the fact that orders related to a private market need a logged in user to open the checkout.

Remove checkout link button for orders with private market

---

apps/orders/src/components/OrderSummary/hooks/useActionButtons.tsx
apps/orders/src/hooks/useOrderDetails.tsx

This PR introduces logic to detect if a capture is asynchronous and its associated job is still pending.
When an async capture is detected, the "Capture" button is shown as disabled, and polling is activated on the order to wait for the capture to complete.

Handle async capture in order details

---

apps/imports/src/components/Details/ImportDate.tsx
apps/imports/src/components/Details/ImportDetails.tsx
apps/imports/src/components/InputParser/templates/coupon.ts
apps/imports/src/components/InputParser/templates/skuListItems.ts
apps/imports/src/components/List/Item.tsx
apps/imports/src/components/List/ItemDescriptionLine.tsx
apps/imports/src/components/List/utils.test.ts
apps/imports/src/components/List/utils.ts
apps/imports/src/pages/DetailsPage.tsx

Closes commercelayer/issues-app#346
- Updated templates for `skus_list`, `gift_cards` and `coupons`
- Replaced `formatDateWithPredicate` for dates
- Added new status "completed with errors" and simplified the icon status component
- Added processed counter in details page

UI improvements in app-imports

---

apps/orders/src/data/filters.ts
apps/orders/src/metricsApi/useCountryCodes.ts
apps/orders/src/pages/Filters.tsx
apps/orders/src/pages/OrderList.tsx

Closes  commercelayer/issues-app#180
I've added the possibility to filter orders by country code (multi-options).
The list of all country codes is fetched using metrics api and then passed to the filters components as an array of value/label.
This approach requires to defer the rendering of listing and filters page only after the countries have been fetched, but since this request is cached and performed only the first time, the delay is unnoticeable.

Allow to filter orders by country

---

apps/bundles/package.json
apps/customers/package.json
apps/exports/package.json
apps/gift_cards/package.json
apps/imports/package.json
apps/inventory/package.json
apps/my_sample_app/package.json
apps/orders/package.json
apps/price_lists/package.json
apps/promotions/package.json
apps/returns/package.json
apps/shipments/package.json
apps/shipments/src/components/FormPackingFieldPackages.tsx
apps/shipments/src/components/FormPackingFieldWeight.tsx
apps/shipments/src/data/filters.ts
apps/shipments/src/pages/Filters.tsx
apps/shipments/src/pages/Home.tsx
apps/shipments/src/pages/ShipmentList.tsx
apps/sku_lists/package.json
apps/skus/package.json
apps/stock_transfers/package.json
apps/subscriptions/package.json
apps/tags/package.json
apps/webhooks/package.json
packages/common/package.json
packages/index/package.json
pnpm-lock.yaml

Closes  commercelayer/issues-app#400
- Updated app-elements
- Add filters in all listing pages (views: picking, packing, ready to ship, on hold). In these views, the filter status is hidden.
- Show reference (in available) in listing pages
- Auto-select first available package and hide unit of weight label in packing form

App shipments improvements (filters lists, show reference and packing form adjustments)

---

apps/exports/src/components/Form/index.tsx
apps/exports/src/components/Form/types.d.ts
apps/exports/src/data/fields.ts
apps/exports/src/pages/NewExportPage.tsx

Closes commercelayer/issues-app#48
- Update UI to have select and checkbox to control format (csv / json) and dry_data (importable)
- Add subset of fields to export orders with the "simple format" controlled checkbox

Enable custom fields subset for orders export

---

apps/promotions/src/components/FlexRuleBuilder.tsx
apps/promotions/src/components/PromotionForm.tsx
apps/promotions/src/data/formConverters/promotion.ts
apps/promotions/src/data/promotions/config.tsx
apps/promotions/src/data/promotions/configs/flex_promotions.tsx
apps/promotions/src/data/promotions/configs/promotions.tsx
apps/promotions/src/main.tsx
apps/promotions/src/mocks/index.ts
apps/promotions/src/mocks/resources/flex_promotions.ts
apps/promotions/src/pages/NewSelectTypePage.tsx
apps/promotions/src/pages/PromotionDetailsPage.tsx

Part of commercelayer/issues-app#370
I added the new `RuleEngine` component to the promotion app. Now, when a user creates a Flex Promotion, they can also use the builder.

Implement new RuleEngine component in the promotion app

---

apps/promotions/src/data/filters.ts
apps/promotions/src/pages/FiltersPage.tsx
apps/promotions/src/pages/HomePage.tsx
apps/promotions/src/pages/PromotionListPage.tsx

Closes commercelayer/issues-app#427
I added the possibility to apply filters to all promotion statuses in the list.

Add filters to all promotion statuses

---

apps/shipments/src/hooks/useViewStatus.tsx

Closes commercelayer/issues-app#342
Closes commercelayer/issues-app#363
- Shipment status can now be reset to picking, even after the shipping label has been purchased.
- Upcoming shipments can now be manually moved to picking status.

Allow to reset shipment status for upcoming and purchased shipments
