commercelayer/dashboard-apps

- apps/bundles/package.json
- apps/bundles/src/pages/BundlesList.tsx
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/skus/src/pages/SkusList.tsx
- apps/stock_transfers/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/app-builder/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Updated all dependencies to the latest major
> Update all dependencies to the latest major

- apps/webhooks/src/pages/EventCallbacksList.tsx
Sort `Event callbacks` list in a descending ordering
> Sort `Event callbacks` list

- apps/stock_transfers/src/components/StockTransferTimeline.tsx
Added missing form behavior to `Stock transfers` timeline
> Add missing form behavior to `Stock transfers` timeline

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/exports/src/pages/DetailsPage.tsx
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/returns/src/pages/ReturnDetails.tsx
- apps/shipments/package.json
- apps/shipments/src/components/ShipmentInfo.tsx
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
- Bumped `app-elements` package to have the latest `ResourceDetails` fix
- Added support for `tags` in `return` details page
> Update `app-elements` and apply refinements

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Updated `app-elements` package in all apps to have the fix for the `ResourceMetadata` form repaint bug on tab change
> Update `app-elements` package

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Updated `app-elements` package to latest version to enable latest fixes on `ResourceMetadata` component
> Update `app-elements` package to latest version

- apps/bundles/package.json
- apps/customers/package.json
- apps/customers/src/pages/CustomerOrders.tsx
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/gift_cards/src/components/ListItemGiftCard.tsx
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/promotions/src/components/CouponTable.tsx
- apps/promotions/src/hooks/useDeleteCouponOverlay.tsx
- apps/promotions/src/pages/CouponListPage.tsx
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/sku_lists/src/components/SkuListManualItems.tsx
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/tags/package.json
- apps/tags/src/components/ListItemTag.tsx
- apps/webhooks/package.json
- apps/webhooks/src/components/ListItemEventCallback.tsx
- apps/webhooks/src/components/ListItemWebhook.tsx
- apps/webhooks/src/pages/EventCallbacksList.tsx
- apps/webhooks/src/pages/WebhooksList.tsx
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Updated from `ResourceList` to `useResourceList` in the following points:
Small improvements
- added skeleton template in webhooks list
- improve delete action on promotions > coupons list page leveraging new `removeItem`
> Update app-elements with `useResourceList`

- apps/skus/src/components/ShippingCategorySelect.tsx
Replaced wrongly edited doc link
- [] Make sure to add/update documentation regarding your changes.
> Replace wrongly edited doc link

- apps/sku_lists/src/components/SkuListForm/SkuListForm.tsx
- apps/sku_lists/src/components/SkuListForm/schema.ts
- apps/sku_lists/src/components/SkuListForm/utils.ts
- apps/sku_lists/src/components/SkuListManualItems.tsx
- apps/sku_lists/src/hooks/useCreateSkuList.tsx
- apps/sku_lists/src/pages/SkuListEdit.tsx
- apps/sku_lists/src/pages/SkuListNew.tsx
Updated `SKU List` form with new selector.
> Update `SKU List` form with new selector

- apps/inventory/src/components/ListItemStockItem.tsx
Closes commercelayer/issues-app/issues/144
Hide reserved stock if quantity is `0`
> Hide reserved stock if quantity is `0`

- apps/sku_lists/src/components/ListItemSkuListItem.tsx
- apps/sku_lists/src/components/SkuListManualItems.tsx
Enhanced Items list of `SKU list` app by:
- Cleaning up items' skeleton elements
- Adding the items counter
> Enhance Items list of `SKU list` app

- apps/skus/src/pages/SkuEdit.tsx
- apps/skus/src/utils/getSkuFromFormValues.ts
Fixed types of update form of `skus` app to improve code readability and SDK types constraints
> Fix types of update form of `skus` app

- apps/promotions/src/data/formConverters/coupon.ts
- apps/promotions/src/pages/PromotionDetailsPage.tsx
Closes commercelayer/issues-app#242
https://github.com/user-attachments/assets/65de8978-61f7-4c16-84d8-f22c127fbd60
> Small improvements to coupons from the promotion app

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Updated `app-elements` package to latest version to include the `formatDate` bugfix
> Update `app-elements` package to latest

- apps/orders/src/data/filters.test.ts
- apps/orders/src/data/filters.ts
Closes  commercelayer/issues-app#233
This pull request introduces a new function, `parseTextSearchValue`, to handle text search values more effectively and includes comprehensive tests for it. Additionally, it integrates this new function into the existing codebase.
* **New Function**: Added `parseTextSearchValue` to handle text search values with various conditions, including handling emails and special characters. (`apps/orders/src/data/filters.ts`)
* **Unit Tests**: Added unit tests for `parseTextSearchValue` to ensure it handles different input scenarios correctly. (`apps/orders/src/data/filters.test.ts`)
* **Integration**: Replaced the inline `parseFormValue` function with `parseTextSearchValue` in the `makeInstructions` function. (`apps/orders/src/data/filters.ts`)
* **Utility …
> Orders - Improve text search logic by detecting email address

- apps/promotions/src/pages/PromotionDetailsPage.tsx
Added support for `tags` in `promotions` app
> Add support for `tags` in `promotions` app

- apps/price_lists/src/pages/Home.tsx
Enhanced home page of `Price lists` app by:
- fixing a copy error in a search bar placeholder
- hiding the search bar if no price lists are available
- hiding also the whole `Browse` section if no price lists are available and showing the old gray empty state inviting the user to create his/her first price list
> Enhance home page of `Price lists` app

- apps/subscriptions/.env
- apps/subscriptions/.eslintrc.cjs
- apps/subscriptions/.gitignore
- apps/subscriptions/.lintstagedrc.json
- apps/subscriptions/LICENSE
- apps/subscriptions/index.html
- apps/subscriptions/package.json
- apps/subscriptions/public/config.js
- apps/subscriptions/public/config.preview-prd.js
- apps/subscriptions/public/config.preview-stg.js
- apps/subscriptions/src/App.tsx
- apps/subscriptions/src/components/ErrorNotFound.tsx
- apps/subscriptions/src/components/ListItemSubscription.tsx
- apps/subscriptions/src/data/dictionaries.ts
- apps/subscriptions/src/data/routes.ts
- apps/subscriptions/src/env.d.ts
- apps/subscriptions/src/hooks/useOrderSubscriptionDetails.tsx
- apps/subscriptions/src/hooks/useTriggerAttribute.ts
- apps/subscriptions/src/main.tsx
- apps/subscriptions/src/mocks/index.ts
- apps/subscriptions/src/mocks/resource.ts
- apps/subscriptions/src/mocks/resources/orderSubscriptions.ts
- apps/subscriptions/src/pages/SubscriptionsList.tsx
- apps/subscriptions/tsconfig.json
- apps/subscriptions/tsconfig.node.json
- apps/subscriptions/vite.config.js
- pnpm-lock.yaml
Created the new `Subscription` app with the order subscriptions listing page
> Setup new `Subscription` app

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
I updated app-elements to the latest.
> Update app-elements to the latest

- apps/promotions/src/components/CouponForm.tsx
- apps/promotions/src/components/ListItemPromotion.tsx
- apps/promotions/src/components/PromotionForm.tsx
- apps/promotions/src/data/filters.ts
- apps/promotions/src/data/formConverters/promotion.ts
- apps/promotions/src/data/promotions/components/PromotionSkuListSelector.tsx
- apps/promotions/src/data/promotions/config.tsx
- apps/promotions/src/data/promotions/configs/flex_promotions.tsx
- apps/promotions/src/data/routes.ts
- apps/promotions/src/data/ruleBuilder/config.tsx
- apps/promotions/src/data/ruleBuilder/currency.tsx
- apps/promotions/src/data/ruleBuilder/form/RuleBuilderForm.tsx
- apps/promotions/src/hooks/useDeletePromotionOverlay.tsx
- apps/promotions/src/pages/NewPromotionActivationRulePage.tsx
- apps/promotions/src/pages/NewSelectTypePage.tsx
- apps/promotions/src/pages/PromotionDetailsPage.tsx
- apps/promotions/src/pages/PromotionListPage.tsx
- apps/promotions/src/types.ts
I created a type of promotion called "Flex promotion". This promotion leverages on a brand new rules-engine.
> Add flex promotions

- apps/price_lists/src/components/ListEmptyStatePrice.tsx
- apps/price_lists/src/pages/Home.tsx
- apps/price_lists/src/pages/PricesList.tsx
- Added new UI for empty states in case of search results
- Fixed the behavior or search result empty state for prices lists with active search
> Refine empty states UI and behavior for `price_lists` app

- apps/promotions/src/data/promotions/configs/flex_promotions.tsx
- apps/promotions/src/pages/NewPromotionPage.tsx
- apps/promotions/src/pages/PromotionDetailsPage.tsx
I added the CodeEditor component to the flex promotions:
> Flex promotions code editor

- packages/index/package.json
- packages/index/src/dependencies.test.ts
- pnpm-lock.yaml
I added a couple of tests for checking that dependencies are fine. This works with the `pnpm-lock.yaml`.
> Add tests for dependencies

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- pnpm-lock.yaml
This PR restore the same version of `react-hook-form` used in `app-elements`
> Restore previous version of react-hook-form

- apps/skus/src/pages/SkuNew.tsx
Closes commercelayer/issues-app/issues/288
Enhanced `skus` app to:
- Save image while creation
- Redirect to created SKU after creation
> Enhance SKU creation behavior

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
> Update app-elements package

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Update `app-elements` package to latest major version.
> Update app-elements to latest major

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/orders/src/hooks/useOrderDetails.tsx
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/shipments/src/pages/ShipmentList.tsx
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Updated app-elements package to enable new shipment list items.
> Update app-elements to enable new shipment list items

- apps/bundles/src/App.tsx
- apps/customers/src/pages/Home.tsx
- apps/gift_cards/src/pages/Home.tsx
- apps/sku_lists/src/App.tsx
- apps/skus/src/App.tsx
- apps/subscriptions/src/App.tsx
- apps/tags/src/App.tsx
Closes #154 
Fixed redirect routes behavior thanks to the external contribution of @maxmezzomo.
> Fix redirect routes behavior

- apps/shipments/src/components/FormPacking.tsx
- apps/shipments/src/components/FormPackingMoreOptions.tsx
Closes commercelayer/issues-app/issues/299
Hid packing custom form if shipment has same origin and destination country.
> Hide packing custom form if shipment has same origin and destination country

- apps/exports/src/data/relationships.ts
Closes commercelayer/issues-app/issues/268
Enabled `stock_line_items` relationship in shipment exports.
> Enable `stock_line_items` relationship in shipment exports

- apps/orders/src/pages/OrderNew.tsx
This PR fixes a regression in the new order page
> Set proper condition in new order page

- apps/promotions/src/pages/CouponListPage.tsx
Closes commercelayer/issues-app/issues/318
Increased paginated coupons per page in promotions.
> Increase paginated coupons per page in promotions

- apps/bundles/package.json
- apps/customers/package.json
- apps/customers/src/hooks/useCustomerDeleteOverlay.tsx
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/orders/src/pages/LinkDetails.tsx
- apps/price_lists/package.json
- apps/price_lists/src/components/PriceListForm.tsx
- apps/promotions/package.json
- apps/promotions/src/pages/NewSelectTypePage.tsx
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/common/src/pages/LinkDetailsPage.tsx
- packages/index/package.json
- packages/index/src/App.tsx
- pnpm-lock.yaml
I updated app-elements to the latest version.
> Update elements to latest version

- apps/exports/@typing/Resources.d.ts
- apps/exports/src/data/relationships.ts
- apps/exports/src/data/resources.ts
Added `returns` resource type in exports app.
> Add `returns` resource type in exports app

- apps/price_lists/src/pages/Home.tsx
Rename `Home` page title of Price lists app to `Prices`.
> Rename Home title of Price lists app

- apps/bundles/package.json
- apps/customers/package.json
- apps/customers/src/pages/CustomerDetails.tsx
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/orders/src/pages/OrderDetails.tsx
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/returns/src/pages/ReturnDetails.tsx
- apps/shipments/package.json
- apps/shipments/src/pages/ShipmentDetails.tsx
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Closes commercelayer/issues-app/issues/339
Added attachments in demanded apps:
- orders
- shipments
- customers
- returns
> Add attachments

- apps/orders/src/components/OrderSummary/hooks/useSummaryRows.tsx
Fixed variable key of order editing totals translation.
> Fix variable key of order editing translation

- apps/shipments/src/mocks/resources/shipments.ts
I set a compatible status in shipment mock to fix icon in skeleton while shipment list is loading.
> Improvement shipment list loading state

- apps/promotions/src/components/CouponForm.tsx
Edited the coupon creation form to manage code min and max length from organization flags.
> Manage coupon code min and max length with organization flag

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Update dependencies to latest minor version.
> Update deps to latest minor

- .github/release.yaml
Added additional labels to github release.
> Add additional labels to github release

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/inventory/src/pages/Home.tsx
- apps/orders/package.json
- apps/price_lists/package.json
- apps/price_lists/src/pages/Home.tsx
- apps/promotions/package.json
- apps/promotions/src/pages/CouponListPage.tsx
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/app-builder/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
- Updated dependencies to latest major version.
- Applied SearchBar margin fix previously made in `app-elements` package where needed in apps.
> Update deps and apply searchbar margin fix

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Bump `elements` to latest minor version
> Bump elements

- apps/shipments/src/components/FormPackingFieldItems.tsx
Avoid using `name` and `image_url` from sku (`stock_line_items`).
> Avoid using `name` and `image_url` from sku (`stock_line_items`)

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/orders/src/components/OrderSummary/hooks/useAddCouponOverlay.tsx
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Bump elements and use calculated coupon min length in validation error.
> Enhance coupon code min length in validation error

- apps/bundles/package.json
- apps/customers/package.json
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/subscriptions/src/components/SubscriptionSteps.tsx
- apps/tags/package.json
- apps/webhooks/package.json
- package.json
- packages/app-builder/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
- Updated deps to latest major version.
- Temporarily forced the patched version of `axios` package to fix an high vulnerability.
> Update deps to latest major version

- apps/bundles/package.json
- apps/customers/package.json
- apps/customers/src/components/CustomerAnonymization.tsx
- apps/customers/src/hooks/useCustomerCanBeAnonymized.tsx
- apps/customers/src/hooks/useCustomerCanBeDeleted.tsx
- apps/customers/src/hooks/useCustomerDeleteOverlay.tsx
- apps/customers/src/hooks/useCustomerDetails.tsx
- apps/customers/src/pages/CustomerDetails.tsx
- apps/exports/package.json
- apps/gift_cards/package.json
- apps/imports/package.json
- apps/inventory/package.json
- apps/orders/package.json
- apps/price_lists/package.json
- apps/promotions/package.json
- apps/returns/package.json
- apps/shipments/package.json
- apps/sku_lists/package.json
- apps/skus/package.json
- apps/stock_transfers/package.json
- apps/subscriptions/package.json
- apps/tags/package.json
- apps/webhooks/package.json
- packages/common/package.json
- packages/index/package.json
- pnpm-lock.yaml
Closes commercelayer/issues-app/issues/195
I added customer anonymization flow in replacement of old delete customer modal shown when the customer was not deletable.
> Add customer anonymization process

- apps/customers/src/hooks/useCustomerCanBeAnonymized.tsx
Fixed anonymization visibility conditions.
> Fix anonymize visibility

- apps/imports/src/components/InputParser/templates/giftCards.ts
I've added the columns `status` and `market_id` in the import gift cards csv template.
> Update `gift_cards` import template

- apps/customers/src/hooks/useCustomerAnonymizedPendingList.tsx
- apps/customers/src/pages/CustomerList.tsx
Closes commercelayer/issues-app/issues/366
Introduced pending anonymization requests in customers list page.
> Show pending anonymization requests in customers list page

- apps/webhooks/src/data/events.ts
Closes commercelayer/issues-app/issues/387
Added `transaction.refused` event in `webhooks` app.
> Add `transaction.refused` event

- apps/customers/src/data/filters.ts
- apps/price_lists/src/data/filters.ts
- apps/returns/src/data/filters.ts
Closes commercelayer/issues-app#371
`app-price_lists`: allow to search by product name and reference in "all prices" 
`app-customers`: search by reference
`app-returns`: search by sku code
> Improve filters instructions

- apps/webhooks/@typing/Resources.d.ts
- apps/webhooks/src/data/events.ts
Closes commercelayer/issues-app/issues/402
Added new anonymizations events to `webhooks` app.
> Add new anonymizations events to `webhooks` app

- apps/promotions/src/pages/PromotionDetailsPage.tsx
Closes commercelayer/issues-app#369
Add the ability to duplicate a flex promotion.
> Add ability to duplicate a flex promotion

- apps/orders/src/components/NewOrder/hooks/useCustomerAddressOverlay.tsx
Closes commercelayer/issues-app#280
https://github.com/user-attachments/assets/29be3a7f-bcc2-4c9b-812b-dd36e4059765
> Allow to set customer address during order editing for both billing and shipping

- apps/exports/src/App.tsx
- apps/exports/src/components/List/Provider.tsx
- apps/exports/src/data/filters.ts
- apps/exports/src/data/routes.ts
- apps/exports/src/pages/Filters.tsx
- apps/exports/src/pages/ListPage.tsx
Closes commercelayer/issues-app#375
Export list can now be filtered.
> Add filters to export list

- apps/imports/src/App.tsx
- apps/imports/src/components/List/Provider.tsx
- apps/imports/src/data/filters.ts
- apps/imports/src/data/resources.ts
- apps/imports/src/data/routes.ts
- apps/imports/src/pages/Filters.tsx
- apps/imports/src/pages/ListPage.tsx
- apps/imports/src/pages/ResourceSelectorPage.tsx
Closes commercelayer/issues-app#417
- Import list can now be filtered
-------
- Updated UI for the resource selector page with search bar
> Add filters in import list

- apps/sku_lists/src/pages/SkuListDetailsAddItems.tsx
Closes commercelayer/issues-app#442
> Optimize API calls in SkuListDetailsAddItems component

- apps/exports/src/data/relationships.ts
Closes commercelayer/issues-app#423
I've added `customer_addresses` and `returns` to customer exports.
> Add more relationship to customer exports

- apps/returns/src/data/filters.ts
Closes commercelayer/issues-app#404
> Remove `return_line_items_line_item_sku_code` predicate from app-returns search filter

- apps/promotions/src/components/FlexRuleBuilder.tsx
Promotion rules are now restored after being saved.
> Promotion rules are now restored after being saved
